### PR TITLE
Laravel 5 support

### PR DESCRIPTION
**Pull request by Stayallive**

### CODE REVIEW

**Comment by machuga** [comment]
Failing due to PHP 5.3 Incompatibility

**Comment by Stayallive** [comment]
Oh right, we would have to bump this to 5.4 minimum since L5 does this... any problems with that?

**Comment by ubald** [comment]
Yes please update and merge, I also had to fork in order to install.

**Comment by machuga** [comment]
As-is I cannot merge it since it's breaking the build. 2.x supports 5.3, but 3.0 won't have to.

**Comment by machuga** [comment]
@Stayallive if you bump the version number to 5.4.0, update the travis.yml file to remove 5.3 and add whatever new php versions there are, I'll merge this in and mark it as a minor version release.  Since you're the one motivating me to make this happen I want to make sure you get the credit in the commit history. :)

**Comment by Stayallive** [comment]
I have updated the travis file to use the one Laravel uses, hope that's cool with you :)

**Comment by machuga** [comment]
Thanks!

**Comment by ghprod** [comment]
Cooll.. L5 welcome :dango:

**Pull request merged**
